name: Github Action Demo
on:
  push:
    branches:
      - main
    paths-ignore: [./github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo " job was trigered by ${{ github.event_name }}"
          echo " the name of the branch is ${{ github.ref }}"
      - uses: actions/checkout@v3.3.0
      - run: tree -a
